### ISSUE TITLE
What do I need to edit in "make_request.py" to make it work? I am not sure where to get the CSRF token from!

### ISSUE THREAD

**Issue by NotErikUden** [michaelshumshum/r-placer#1]
Yeah, sorry. I've never worked with the Reddit API so it would be nice if I could get a tiny introduction on what I need to do to make this work (if you find the time for that).
Additionally, it would be nice knowing what to edit in order to make the bot place pixels on certain coordinates! Just like some // comments in the code would be nice to show newcomers like myself what to do, since I really do not understand what is going on as your code seems really advanced for my standards.

**Comment by michaelshumshum** [comment]
the csrf token is automatically obtained, so you don't have to worry about it. though, if you are a newcomer, i think your priority should be learning python, instead of doing this, as it isn't really straightforward and all of us are still figuring it out. 

right now, not much is functional, but the code SHOULD'VE worked, but it didn't. to use it, make a new python file in the folder with whatever name. at the top of the file, add `import make_request`. next, add `make_request.make(username,password,coordinates,colorindex)`, where username password is your login and coordinates is the coordinates you want for the pixel in a tuple form like `(x,y)` and the color index is the color you want. i am not sure what colors are what numbers, but we can figure that out soon.

don't be surprised if nothing works or if you can't understand anything. i started this 2 hours ago.

**Comment by brandii-co** [comment]
> the csrf token is automatically obtained, so you don't have to worry about it. though, if you are a newcomer, i think your priority should be learning python, instead of doing this, as it isn't really straightforward and all of us are still figuring it out.
> 
> right now, not much is functional, but the code SHOULD'VE worked, but it didn't. to use it, make a new python file in the folder with whatever name. at the top of the file, add `import make_request`. next, add `make_request.make(username,password,coordinates,colorindex)`, where username password is your login and coordinates is the coordinates you want for the pixel in a tuple form like `(x,y)` and the color index is the color you want. i am not sure what colors are what numbers, but we can figure that out soon.
> 
> don't be surprised if nothing works or if you can't understand anything. i started this 2 hours ago.

These might be the color indices commented on the other placer repo:
https://github.com/CicadaCinema/place-bot/issues/1#issuecomment-1086160505

<details>
  <summary>color indices</summary>
<pre>
[
    {
        "hex": "#FF4500",
        "index": 2,
        "__typename": "Color"
    },
    {
        "hex": "#FFA800",
        "index": 3,
        "__typename": "Color"
    },
    {
        "hex": "#FFD635",
        "index": 4,
        "__typename": "Color"
    },
    {
        "hex": "#00A368",
        "index": 6,
        "__typename": "Color"
    },
    {
        "hex": "#7EED56",
        "index": 8,
        "__typename": "Color"
    },
    {
        "hex": "#2450A4",
        "index": 12,
        "__typename": "Color"
    },
    {
        "hex": "#3690EA",
        "index": 13,
        "__typename": "Color"
    },
    {
        "hex": "#51E9F4",
        "index": 14,
        "__typename": "Color"
    },
    {
        "hex": "#811E9F",
        "index": 18,
        "__typename": "Color"
    },
    {
        "hex": "#B44AC0",
        "index": 19,
        "__typename": "Color"
    },
    {
        "hex": "#FF99AA",
        "index": 23,
        "__typename": "Color"
    },
    {
        "hex": "#9C6926",
        "index": 25,
        "__typename": "Color"
    },
    {
        "hex": "#000000",
        "index": 27,
        "__typename": "Color"
    },
    {
        "hex": "#898D90",
        "index": 29,
        "__typename": "Color"
    },
    {
        "hex": "#D4D7D9",
        "index": 30,
        "__typename": "Color"
    },
    {
        "hex": "#FFFFFF",
        "index": 31,
        "__typename": "Color"
    }
]
 </pre>
</details>

**Comment by michaelshumshum** [comment]
not an issue
